name: .editorconfig generator

permissions:
  contents: write

on:
  push: # Run on every push regardless of the branch
    paths:
      - 'parts/**.editorconfig' # Only react to parts being modified
      - '.github/workflows/generator.yml' # React to the workflow file itself changing

  workflow_dispatch: # Allow manual runs for when the generator / output format is updated

jobs:
  generate_editorconfig:
    runs-on: ubuntu-latest
    name: Generating the merged .editorconfig file

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - name: Install the .NET workflow
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build the generator project
      run: dotnet build src/Generator

    - name: Run the generator project
      working-directory: src/Generator/bin/Debug/net9.0
      run: ./Generator

    - name: Ensure .editorconfig file exists so that staging without changes doesn't fail
      run: touch .editorconfig

    - name: Stage the generated .editorconfig file
      run: git add .editorconfig

    - name: Check if the generated .editorconfig file actually changed
      id: check_changes
      run: |
        if [[ -z $(git status -s) ]]; then
          echo "The .editorconfig file has not changed, git commit will be skipped."
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "The .editorconfig file has changed."
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Configure git information
      if: steps.check_changes.outputs.has_changes == 'true'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Create the commit with the new .editorconfig file
      if: steps.check_changes.outputs.has_changes == 'true'
      run: git commit -m "* Updated the generated .editorconfig file."

    - name: Push the new commit
      if: steps.check_changes.outputs.has_changes == 'true'
      run: git push
