name: notify

on:
  push:
    branches: main
    paths:
      - '.editorconfig' # React to the .editorconfig file being modified

  workflow_dispatch: # Allow manual runs for when the workflow is changed enough to need to be dispatched

jobs:
  notify:
    runs-on: ubuntu-latest
    name: Notify

    strategy:
      matrix:
        repository: [
          .github,

          Polyease,
          Common,
          Testing,

          Documentation,
          Sain,
          Media,
          Console,
          Markdown,

          Owldoc
        ]

    steps:
      - name: Notify the owl-domain/${{ matrix.repository }} repository
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_PAT }}
          repository: owl-domain/${{ matrix.repository }}
          event-type: editorconfig-update
